package au.com.notes.constants;

public class DelimiterConstants {
	public static final String SPACE = " ";
	public static final String COMMA = ",";
	public static final String FULLSTOP = ".";
	public static final String UNDERSCORE = "_";
	public static final String COLON = ":";
	public static final String SEMICOLON = ";";
	public static final String QUESTION_MARK = "?";
	public static final String EXPLAINATION_MARK = "!";
	public static final String AMPERSAND = "&";
	public static final String DOLLAR = "$";
	public static final String HASH = "#";
	public static final String AT = "@";
	public static final String FORWARD_SLASH = "/";
	public static final String BACK_SLASH = "\\";
	public static final String DOUBLE_BACK_SLASH = "\\\\";
	public static final String DASH = "-";
	public static final String PIPE = "|";
	public static final String PERCENT = "%";
	public static final String HAT = "^";
	public static final String STAR = "*";
	public static final String PLUS = "+";
	public static final String MINUS = "-";
	public static final String EQUALS = "=";
	public static final String TILDA = "~";
	public static final String APOSTRAPHE = "`";
	public static final String CARRIAGE_RETRUN = "\r";
	public static final String NEWLINE = "\n";
	public static final String TAB = "\t";
	public static final String QUOTE_DOUBLE = "\"";
	public static final String QUOTE_DOUBLE_TWO = "\"\"";
	public static final String QUOTE_SINGLE = "'";
	public static final String QUOTE_SINGLE_TWO = "''";
	public static final String BRACKET_ROUND_OPEN = "(";
	public static final String BRACKET_ROUND_CLOSE = ")";
	public static final String BRACKET_SQUARE_OPEN = "[";
	public static final String BRACKET_SQUARE_CLOSE = "]";
	public static final String BRACKET_CURLY_OPEN = "{";
	public static final String BRACKET_CURLY_CLOSE = "}";
	public static final String BRACKET_ANGLE_OPEN = "<";
	public static final String BRACKET_ANGLE_CLOSE = ">";
}
